; Maximum allowed size for uploaded files.
upload_max_filesize = 10G

; Must be larger than or equal to upload_max_filesize.
post_max_size = 10100M

; Maximum number of files that can be uploaded via a single request.
max_file_uploads = 50

; Increase execution and input time for large transfers.
max_execution_time = 0
max_input_time = 600
memory_limit = 512M
